### ISSUE TITLE
java.lang.NullPointerException: Location doesn't exist

### ISSUE THREAD

**Issue by jayeshbabuav** [imperiumlabs/GeoFirestore-Android#34]
When I run the following code, 
```
geoFirestore.getLocation(getItem("documentId", new GeoFirestore.LocationCallback()
                {
                    @Override
                    public void onComplete(GeoPoint geoPoint, Exception e)
                    {
                           e.printStackTrace();
                    }
                });
```
I get this exception:

```
java.lang.NullPointerException: Location doesn't exist
2019-08-30 14:32:01.322 2834-2834/in.hashcoder.dishyumm W/System.err:     at org.imperiumlabs.geofirestore.GeoFirestore$getLocation$2.onSuccess(GeoFirestore.kt:195)
2019-08-30 14:32:01.322 2834-2834/in.hashcoder.dishyumm W/System.err:     at org.imperiumlabs.geofirestore.GeoFirestore$getLocation$2.onSuccess(GeoFirestore.kt:16)
2019-08-30 14:32:01.322 2834-2834/in.hashcoder.dishyumm W/System.err:     at com.google.android.gms.tasks.zzn.run(Unknown Source:4)
2019-08-30 14:32:01.323 2834-2834/in.hashcoder.dishyumm W/System.err:     at android.os.Handler.handleCallback(Handler.java:873)
2019-08-30 14:32:01.323 2834-2834/in.hashcoder.dishyumm W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:99)
2019-08-30 14:32:01.323 2834-2834/in.hashcoder.dishyumm W/System.err:     at android.os.Looper.loop(Looper.java:214)
2019-08-30 14:32:01.323 2834-2834/in.hashcoder.dishyumm W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6986)
2019-08-30 14:32:01.323 2834-2834/in.hashcoder.dishyumm W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2019-08-30 14:32:01.323 2834-2834/in.hashcoder.dishyumm W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
2019-08-30 14:32:01.323 2834-2834/in.hashcoder.dishyumm W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)
```

My `setLocation()` works fine and location is getting entered in database fine.

**Comment by Supercaly** [comment]
What's doing the function `getItem()`?

**Comment by jayeshbabuav** [comment]
sorry I forgot to remove that getItem() while copying the code:

`geoFirestore.getLocation("documentId", new GeoFirestore.LocationCallback()
                {
                    @Override
                    public void onComplete(GeoPoint geoPoint, Exception e)
                    {
                           e.printStackTrace();
                    }
                });`

this is the actual code

**Comment by Supercaly** [comment]
The function returns a `NullPointerException` because the queried geolocation is null; this can depend on two factors:
1. In the database, your data is not set correctly with "l" and "g" fields
2. The "l" field of your data is not correctly set, it needs to be a `GeoPoint` or a `List<Double>`

**Comment by bhavin-chauhan** [comment]
> sorry I forgot to remove that getItem() while copying the code:
> 
> ```
> geoFirestore.getLocation("documentId", new GeoFirestore.LocationCallback()
>                 {
>                     @Override
>                     public void onComplete(GeoPoint geoPoint, Exception e)
>                     {
>                            e.printStackTrace();
>                     }
>                 });
> ```
> 
> this is the actual code



> The function returns a `NullPointerException` because the queried geolocation is null; this can depend on two factors:
> 
> 1. In the database, your data is not set correctly with "l" and "g" fields
> 2. The "l" field of your data is not correctly set, it needs to be a `GeoPoint` or a `List<Double>`

I am facing same issue and I've checked my firestore database there is entry of l and g

**Comment by bhavin-chauhan** [comment]
> sorry I forgot to remove that getItem() while copying the code:
> 
> ```
> geoFirestore.getLocation("documentId", new GeoFirestore.LocationCallback()
>                 {
>                     @Override
>                     public void onComplete(GeoPoint geoPoint, Exception e)
>                     {
>                            e.printStackTrace();
>                     }
>                 });
> ```
> 
> this is the actual code
how you solved this issue, Can you please guide me so I can check my issue

**Comment by jayeshbabuav** [comment]
instead of using `geoFirestore.getLocation()`, i used `geoFirestore.queryAtLocation(new GeoPoint(latitude, longitude), 10)`
